services:
  - type: web
    name: resume-analyzer
    runtime: docker
    dockerfile: ../Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
    region: oregon
    plan: free
    autoDeploy: true
